
import { WordList } from '../types';

export const englishWordLists: WordList[] = [
  {
    id: 'en-basics',
    name: 'Basic Words',
    description: 'Common everyday words for beginners',
    words: [
      { id: 'en-1', text: 'apple', difficulty: 'easy', hint: 'A red fruit' },
      { id: 'en-2', text: 'banana', difficulty: 'easy', hint: 'A yellow fruit' },
      { id: 'en-3', text: 'cat', difficulty: 'easy', hint: 'A furry pet' },
      { id: 'en-4', text: 'dog', difficulty: 'easy', hint: 'Man\'s best friend' },
      { id: 'en-5', text: 'elephant', difficulty: 'medium', hint: 'A large animal with a trunk' },
      { id: 'en-6', text: 'flower', difficulty: 'medium', hint: 'Grows in gardens' },
      { id: 'en-7', text: 'giraffe', difficulty: 'medium', hint: 'An animal with a long neck' },
      { id: 'en-8', text: 'house', difficulty: 'easy', hint: 'Where people live' },
    ],
    languageId: 'en',
    difficulty: 'easy',
  },
  {
    id: 'en-animals',
    name: 'Animals',
    description: 'Words related to animals and wildlife',
    words: [
      { id: 'en-a1', text: 'tiger', difficulty: 'medium', hint: 'Striped big cat' },
      { id: 'en-a2', text: 'penguin', difficulty: 'medium', hint: 'Bird that can\'t fly but swims' },
      { id: 'en-a3', text: 'zebra', difficulty: 'medium', hint: 'Has black and white stripes' },
      { id: 'en-a4', text: 'kangaroo', difficulty: 'hard', hint: 'Has a pouch for its baby' },
      { id: 'en-a5', text: 'dolphin', difficulty: 'medium', hint: 'Smart sea mammal' },
      { id: 'en-a6', text: 'octopus', difficulty: 'hard', hint: 'Has eight arms' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-food',
    name: 'International Foods',
    description: 'Foods from around the world',
    words: [
      { id: 'en-food-1', text: 'pizza', difficulty: 'easy', hint: 'Italian dish with cheese and toppings' },
      { id: 'en-food-2', text: 'sushi', difficulty: 'medium', hint: 'Japanese dish with rice and fish' },
      { id: 'en-food-3', text: 'burger', difficulty: 'easy', hint: 'Sandwich with a meat patty' },
      { id: 'en-food-4', text: 'pasta', difficulty: 'easy', hint: 'Italian noodles' },
      { id: 'en-food-5', text: 'taco', difficulty: 'easy', hint: 'Mexican folded tortilla with filling' },
      { id: 'en-food-6', text: 'curry', difficulty: 'medium', hint: 'Spicy dish from India' },
    ],
    languageId: 'en',
    difficulty: 'easy',
  },
  {
    id: 'en-places',
    name: 'Famous Places',
    description: 'Well-known locations around the world',
    words: [
      { id: 'en-places-1', text: 'London', difficulty: 'easy', hint: 'Capital of England' },
      { id: 'en-places-2', text: 'Paris', difficulty: 'easy', hint: 'City with the Eiffel Tower' },
      { id: 'en-places-3', text: 'Tokyo', difficulty: 'medium', hint: 'Capital of Japan' },
      { id: 'en-places-4', text: 'Egypt', difficulty: 'medium', hint: 'Country with pyramids' },
      { id: 'en-places-5', text: 'Amazon', difficulty: 'medium', hint: 'World\'s largest rainforest' },
      { id: 'en-places-6', text: 'Africa', difficulty: 'easy', hint: 'Continent with many animals' },
      { id: 'en-places-7', text: 'Stonehenge', difficulty: 'hard', hint: 'Prehistoric monument in England' },
      { id: 'en-places-8', text: 'Colosseum', difficulty: 'medium', hint: 'Ancient amphitheater in Rome' },
      { id: 'en-places-9', text: 'Acropolis', difficulty: 'hard', hint: 'Ancient citadel in Athens' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-stories',
    name: 'Stories & Characters',
    description: 'Characters from famous stories and books',
    words: [
      { id: 'en-stories-1', text: 'dragon', difficulty: 'medium', hint: 'Mythical fire-breathing creature' },
      { id: 'en-stories-2', text: 'wizard', difficulty: 'medium', hint: 'Person who uses magic' },
      { id: 'en-stories-3', text: 'princess', difficulty: 'medium', hint: 'Royal daughter' },
      { id: 'en-stories-4', text: 'pirate', difficulty: 'medium', hint: 'Sails the seas looking for treasure' },
      { id: 'en-stories-5', text: 'knight', difficulty: 'medium', hint: 'Wears armor and serves a king' },
      { id: 'en-stories-6', text: 'fairy', difficulty: 'easy', hint: 'Tiny magical being with wings' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-heritage',
    name: 'Heritage Buildings',
    description: 'Famous historical buildings and monuments',
    words: [
      { id: 'en-heritage-1', text: 'cathedral', difficulty: 'medium', hint: 'Large Christian church' },
      { id: 'en-heritage-2', text: 'palace', difficulty: 'easy', hint: 'Royal residence' },
      { id: 'en-heritage-3', text: 'abbey', difficulty: 'hard', hint: 'Monastery or convent' },
      { id: 'en-heritage-4', text: 'castle', difficulty: 'easy', hint: 'Fortified structure with thick walls' },
      { id: 'en-heritage-5', text: 'tower', difficulty: 'easy', hint: 'Tall narrow building' },
      { id: 'en-heritage-6', text: 'parliament', difficulty: 'medium', hint: 'Building where laws are made' },
      { id: 'en-heritage-7', text: 'lighthouse', difficulty: 'medium', hint: 'Tower with light to guide ships' },
      { id: 'en-heritage-8', text: 'mansion', difficulty: 'medium', hint: 'Large impressive house' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-transport',
    name: 'Historical Transport',
    description: 'Traditional and historical modes of transportation',
    words: [
      { id: 'en-trans-1', text: 'hansom', difficulty: 'hard', hint: 'Two-wheeled horse-drawn cab' },
      { id: 'en-trans-2', text: 'palanquin', difficulty: 'hard', hint: 'Covered sedan chair carried on poles' },
      { id: 'en-trans-3', text: 'stagecoach', difficulty: 'medium', hint: 'Horse-drawn coach for passengers' },
      { id: 'en-trans-4', text: 'sedan', difficulty: 'medium', hint: 'Chair carried by people' },
      { id: 'en-trans-5', text: 'carriage', difficulty: 'medium', hint: 'Horse-drawn vehicle with four wheels' },
      { id: 'en-trans-6', text: 'gondola', difficulty: 'medium', hint: 'Venetian rowing boat' },
      { id: 'en-trans-7', text: 'segway', difficulty: 'medium', hint: 'Self-balancing personal transporter' },
      { id: 'en-trans-8', text: 'rickshaw', difficulty: 'medium', hint: 'Two-wheeled passenger cart' },
    ],
    languageId: 'en',
    difficulty: 'hard',
  },
  {
    id: 'en-heroes',
    name: 'Historical Figures',
    description: 'Famous heroes and historical figures',
    words: [
      { id: 'en-hero-1', text: 'Shakespeare', difficulty: 'medium', hint: 'Famous English playwright' },
      { id: 'en-hero-2', text: 'Einstein', difficulty: 'medium', hint: 'Physicist who developed theory of relativity' },
      { id: 'en-hero-3', text: 'Nightingale', difficulty: 'hard', hint: 'Founder of modern nursing' },
      { id: 'en-hero-4', text: 'Gandhi', difficulty: 'medium', hint: 'Indian leader who advocated non-violence' },
      { id: 'en-hero-5', text: 'Mandela', difficulty: 'medium', hint: 'South African anti-apartheid leader' },
      { id: 'en-hero-6', text: 'Curie', difficulty: 'medium', hint: 'Scientist who discovered radium' },
      { id: 'en-hero-7', text: 'Churchill', difficulty: 'medium', hint: 'British Prime Minister during WWII' },
      { id: 'en-hero-8', text: 'Tubman', difficulty: 'hard', hint: 'Abolitionist who rescued enslaved people' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-professions',
    name: 'Traditional Professions',
    description: 'Historical and traditional occupations',
    words: [
      { id: 'en-prof-1', text: 'blacksmith', difficulty: 'medium', hint: 'Works with iron and steel' },
      { id: 'en-prof-2', text: 'cooper', difficulty: 'hard', hint: 'Makes wooden barrels' },
      { id: 'en-prof-3', text: 'cobbler', difficulty: 'hard', hint: 'Repairs shoes' },
      { id: 'en-prof-4', text: 'miller', difficulty: 'medium', hint: 'Operates a grain mill' },
      { id: 'en-prof-5', text: 'potter', difficulty: 'medium', hint: 'Makes pottery and ceramics' },
      { id: 'en-prof-6', text: 'scribe', difficulty: 'hard', hint: 'Copies documents by hand' },
      { id: 'en-prof-7', text: 'weaver', difficulty: 'medium', hint: 'Makes cloth on a loom' },
      { id: 'en-prof-8', text: 'tanner', difficulty: 'hard', hint: 'Prepares animal hides for leather' },
    ],
    languageId: 'en',
    difficulty: 'hard',
  }
];
