import { WordList } from '../types';

export const englishWordLists: WordList[] = [
  {
    id: 'en-basics',
    name: 'Basic Words',
    description: 'Common everyday words for beginners',
    words: [
      { id: 'en-1', text: 'apple', difficulty: 'easy', hint: 'A red fruit', category: 'food' },
      { id: 'en-2', text: 'banana', difficulty: 'easy', hint: 'A yellow fruit', category: 'food' },
      { id: 'en-3', text: 'cat', difficulty: 'easy', hint: 'A furry pet', category: 'animal' },
      { id: 'en-4', text: 'dog', difficulty: 'easy', hint: 'Man\'s best friend', category: 'animal' },
      { id: 'en-5', text: 'elephant', difficulty: 'medium', hint: 'A large animal with a trunk', category: 'animal' },
      { id: 'en-6', text: 'flower', difficulty: 'medium', hint: 'Grows in gardens', category: 'plant' },
      { id: 'en-7', text: 'giraffe', difficulty: 'medium', hint: 'An animal with a long neck', category: 'animal' },
      { id: 'en-8', text: 'house', difficulty: 'easy', hint: 'Where people live', category: 'building' },
    ],
    languageId: 'en',
    difficulty: 'easy',
  },
  {
    id: 'en-animals',
    name: 'Animals',
    description: 'Words related to animals and wildlife',
    words: [
      { id: 'en-a1', text: 'tiger', difficulty: 'medium', hint: 'Striped big cat', category: 'animal' },
      { id: 'en-a2', text: 'penguin', difficulty: 'medium', hint: 'Bird that can\'t fly but swims', category: 'animal' },
      { id: 'en-a3', text: 'zebra', difficulty: 'medium', hint: 'Has black and white stripes', category: 'animal' },
      { id: 'en-a4', text: 'kangaroo', difficulty: 'hard', hint: 'Has a pouch for its baby', category: 'animal' },
      { id: 'en-a5', text: 'dolphin', difficulty: 'medium', hint: 'Smart sea mammal', category: 'animal' },
      { id: 'en-a6', text: 'octopus', difficulty: 'hard', hint: 'Has eight arms', category: 'animal' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-food',
    name: 'International Foods',
    description: 'Foods from around the world',
    words: [
      { id: 'en-food-1', text: 'pizza', difficulty: 'easy', hint: 'Italian dish with cheese and toppings', category: 'food' },
      { id: 'en-food-2', text: 'sushi', difficulty: 'medium', hint: 'Japanese dish with rice and fish', category: 'food' },
      { id: 'en-food-3', text: 'burger', difficulty: 'easy', hint: 'Sandwich with a meat patty', category: 'food' },
      { id: 'en-food-4', text: 'pasta', difficulty: 'easy', hint: 'Italian noodles', category: 'food' },
      { id: 'en-food-5', text: 'taco', difficulty: 'easy', hint: 'Mexican folded tortilla with filling', category: 'food' },
      { id: 'en-food-6', text: 'curry', difficulty: 'medium', hint: 'Spicy dish from India', category: 'food' },
    ],
    languageId: 'en',
    difficulty: 'easy',
  },
  {
    id: 'en-places',
    name: 'Famous Places',
    description: 'Well-known locations around the world',
    words: [
      { id: 'en-places-1', text: 'London', difficulty: 'easy', hint: 'Capital of England', category: 'place' },
      { id: 'en-places-2', text: 'Paris', difficulty: 'easy', hint: 'City with the Eiffel Tower', category: 'place' },
      { id: 'en-places-3', text: 'Tokyo', difficulty: 'medium', hint: 'Capital of Japan', category: 'place' },
      { id: 'en-places-4', text: 'Egypt', difficulty: 'medium', hint: 'Country with pyramids', category: 'place' },
      { id: 'en-places-5', text: 'Amazon', difficulty: 'medium', hint: 'World\'s largest rainforest', category: 'place' },
      { id: 'en-places-6', text: 'Africa', difficulty: 'easy', hint: 'Continent with many animals', category: 'place' },
      { id: 'en-places-7', text: 'Stonehenge', difficulty: 'hard', hint: 'Prehistoric monument in England', category: 'place' },
      { id: 'en-places-8', text: 'Colosseum', difficulty: 'medium', hint: 'Ancient amphitheater in Rome', category: 'place' },
      { id: 'en-places-9', text: 'Acropolis', difficulty: 'hard', hint: 'Ancient citadel in Athens', category: 'place' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-stories',
    name: 'Stories & Characters',
    description: 'Characters from famous stories and books',
    words: [
      { id: 'en-stories-1', text: 'dragon', difficulty: 'medium', hint: 'Mythical fire-breathing creature', category: 'story' },
      { id: 'en-stories-2', text: 'wizard', difficulty: 'medium', hint: 'Person who uses magic', category: 'story' },
      { id: 'en-stories-3', text: 'princess', difficulty: 'medium', hint: 'Royal daughter', category: 'story' },
      { id: 'en-stories-4', text: 'pirate', difficulty: 'medium', hint: 'Sails the seas looking for treasure', category: 'story' },
      { id: 'en-stories-5', text: 'knight', difficulty: 'medium', hint: 'Wears armor and serves a king', category: 'story' },
      { id: 'en-stories-6', text: 'fairy', difficulty: 'easy', hint: 'Tiny magical being with wings', category: 'story' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-heritage',
    name: 'Heritage Buildings',
    description: 'Famous historical buildings and monuments',
    words: [
      { id: 'en-heritage-1', text: 'cathedral', difficulty: 'medium', hint: 'Large Christian church', category: 'building' },
      { id: 'en-heritage-2', text: 'palace', difficulty: 'easy', hint: 'Royal residence', category: 'building' },
      { id: 'en-heritage-3', text: 'abbey', difficulty: 'hard', hint: 'Monastery or convent', category: 'building' },
      { id: 'en-heritage-4', text: 'castle', difficulty: 'easy', hint: 'Fortified structure with thick walls', category: 'building' },
      { id: 'en-heritage-5', text: 'tower', difficulty: 'easy', hint: 'Tall narrow building', category: 'building' },
      { id: 'en-heritage-6', text: 'parliament', difficulty: 'medium', hint: 'Building where laws are made', category: 'building' },
      { id: 'en-heritage-7', text: 'lighthouse', difficulty: 'medium', hint: 'Tower with light to guide ships', category: 'building' },
      { id: 'en-heritage-8', text: 'mansion', difficulty: 'medium', hint: 'Large impressive house', category: 'building' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-transport',
    name: 'Historical Transport',
    description: 'Traditional and historical modes of transportation',
    words: [
      { id: 'en-trans-1', text: 'hansom', difficulty: 'hard', hint: 'Two-wheeled horse-drawn cab', category: 'transport' },
      { id: 'en-trans-2', text: 'palanquin', difficulty: 'hard', hint: 'Covered sedan chair carried on poles', category: 'transport' },
      { id: 'en-trans-3', text: 'stagecoach', difficulty: 'medium', hint: 'Horse-drawn coach for passengers', category: 'transport' },
      { id: 'en-trans-4', text: 'sedan', difficulty: 'medium', hint: 'Chair carried by people', category: 'transport' },
      { id: 'en-trans-5', text: 'carriage', difficulty: 'medium', hint: 'Horse-drawn vehicle with four wheels', category: 'transport' },
      { id: 'en-trans-6', text: 'gondola', difficulty: 'medium', hint: 'Venetian rowing boat', category: 'transport' },
      { id: 'en-trans-7', text: 'segway', difficulty: 'medium', hint: 'Self-balancing personal transporter', category: 'transport' },
      { id: 'en-trans-8', text: 'rickshaw', difficulty: 'medium', hint: 'Two-wheeled passenger cart', category: 'transport' },
    ],
    languageId: 'en',
    difficulty: 'hard',
  },
  {
    id: 'en-heroes',
    name: 'Historical Figures',
    description: 'Famous heroes and historical figures',
    words: [
      { id: 'en-hero-1', text: 'Shakespeare', difficulty: 'medium', hint: 'Famous English playwright', category: 'figure' },
      { id: 'en-hero-2', text: 'Einstein', difficulty: 'medium', hint: 'Physicist who developed theory of relativity', category: 'figure' },
      { id: 'en-hero-3', text: 'Nightingale', difficulty: 'hard', hint: 'Founder of modern nursing', category: 'figure' },
      { id: 'en-hero-4', text: 'Gandhi', difficulty: 'medium', hint: 'Indian leader who advocated non-violence', category: 'figure' },
      { id: 'en-hero-5', text: 'Mandela', difficulty: 'medium', hint: 'South African anti-apartheid leader', category: 'figure' },
      { id: 'en-hero-6', text: 'Curie', difficulty: 'medium', hint: 'Scientist who discovered radium', category: 'figure' },
      { id: 'en-hero-7', text: 'Churchill', difficulty: 'medium', hint: 'British Prime Minister during WWII', category: 'figure' },
      { id: 'en-hero-8', text: 'Tubman', difficulty: 'hard', hint: 'Abolitionist who rescued enslaved people', category: 'figure' },
    ],
    languageId: 'en',
    difficulty: 'medium',
  },
  {
    id: 'en-professions',
    name: 'Traditional Professions',
    description: 'Historical and traditional occupations',
    words: [
      { id: 'en-prof-1', text: 'blacksmith', difficulty: 'medium', hint: 'Works with iron and steel', category: 'profession' },
      { id: 'en-prof-2', text: 'cooper', difficulty: 'hard', hint: 'Makes wooden barrels', category: 'profession' },
      { id: 'en-prof-3', text: 'cobbler', difficulty: 'hard', hint: 'Repairs shoes', category: 'profession' },
      { id: 'en-prof-4', text: 'miller', difficulty: 'medium', hint: 'Operates a grain mill', category: 'profession' },
      { id: 'en-prof-5', text: 'potter', difficulty: 'medium', hint: 'Makes pottery and ceramics', category: 'profession' },
      { id: 'en-prof-6', text: 'scribe', difficulty: 'hard', hint: 'Copies documents by hand', category: 'profession' },
      { id: 'en-prof-7', text: 'weaver', difficulty: 'medium', hint: 'Makes cloth on a loom', category: 'profession' },
      { id: 'en-prof-8', text: 'tanner', difficulty: 'hard', hint: 'Prepares animal hides for leather', category: 'profession' },
    ],
    languageId: 'en',
    difficulty: 'hard',
  }
];
