
import { WordList } from '../types';

export const spanishWordLists: WordList[] = [
  {
    id: 'es-basics',
    name: 'Palabras Básicas',
    description: 'Palabras comunes para principiantes',
    words: [
      { id: 'es-1', text: 'manzana', difficulty: 'easy', hint: 'fruta roja' },
      { id: 'es-2', text: 'plátano', difficulty: 'easy', hint: 'fruta amarilla' },
      { id: 'es-3', text: 'gato', difficulty: 'easy', hint: 'animal doméstico' },
      { id: 'es-4', text: 'perro', difficulty: 'easy', hint: 'mejor amigo del hombre' },
      { id: 'es-5', text: 'elefante', difficulty: 'medium', hint: 'animal grande con trompa' },
      { id: 'es-6', text: 'flor', difficulty: 'easy', hint: 'crece en jardines' },
      { id: 'es-7', text: 'jirafa', difficulty: 'medium', hint: 'animal con cuello largo' },
      { id: 'es-8', text: 'casa', difficulty: 'easy', hint: 'donde vivimos' },
    ],
    languageId: 'es',
    difficulty: 'easy',
  },
  {
    id: 'es-comida',
    name: 'Comida Latina',
    description: 'Platos típicos de Latinoamérica y España',
    words: [
      { id: 'es-food-1', text: 'paella', difficulty: 'medium', hint: 'plato de arroz español' },
      { id: 'es-food-2', text: 'tacos', difficulty: 'easy', hint: 'comida mexicana' },
      { id: 'es-food-3', text: 'tortilla', difficulty: 'easy', hint: 'hecha con huevos o maíz' },
      { id: 'es-food-4', text: 'churros', difficulty: 'medium', hint: 'postre frito con azúcar' },
      { id: 'es-food-5', text: 'empanada', difficulty: 'medium', hint: 'masa rellena horneada' },
      { id: 'es-food-6', text: 'tamales', difficulty: 'hard', hint: 'envueltos en hojas de maíz' },
    ],
    languageId: 'es',
    difficulty: 'medium',
  },
  {
    id: 'es-lugares',
    name: 'Lugares Hispanos',
    description: 'Lugares famosos en países de habla hispana',
    words: [
      { id: 'es-places-1', text: 'Barcelona', difficulty: 'medium', hint: 'ciudad con la Sagrada Familia' },
      { id: 'es-places-2', text: 'Andes', difficulty: 'medium', hint: 'cordillera en Sudamérica' },
      { id: 'es-places-3', text: 'México', difficulty: 'easy', hint: 'país al sur de Estados Unidos' },
      { id: 'es-places-4', text: 'Amazonas', difficulty: 'medium', hint: 'río más caudaloso del mundo' },
      { id: 'es-places-5', text: 'Madrid', difficulty: 'easy', hint: 'capital de España' },
      { id: 'es-places-6', text: 'Alhambra', difficulty: 'hard', hint: 'palacio y fortaleza en Granada' },
      { id: 'es-places-7', text: 'Machu Picchu', difficulty: 'hard', hint: 'antigua ciudad inca en Perú' },
      { id: 'es-places-8', text: 'Habana Vieja', difficulty: 'medium', hint: 'centro histórico de La Habana' },
    ],
    languageId: 'es',
    difficulty: 'medium',
  },
  {
    id: 'es-cultura',
    name: 'Cultura Hispana',
    description: 'Elementos culturales del mundo hispano',
    words: [
      { id: 'es-culture-1', text: 'guitarra', difficulty: 'medium', hint: 'instrumento musical de cuerdas' },
      { id: 'es-culture-2', text: 'flamenco', difficulty: 'medium', hint: 'baile tradicional español' },
      { id: 'es-culture-3', text: 'piñata', difficulty: 'medium', hint: 'se rompe en fiestas' },
      { id: 'es-culture-4', text: 'siesta', difficulty: 'easy', hint: 'descanso después de comer' },
      { id: 'es-culture-5', text: 'mariachi', difficulty: 'hard', hint: 'música tradicional mexicana' },
    ],
    languageId: 'es',
    difficulty: 'medium',
  },
  {
    id: 'es-profesiones',
    name: 'Profesiones Tradicionales',
    description: 'Oficios y profesiones tradicionales en el mundo hispano',
    words: [
      { id: 'es-prof-1', text: 'alfarero', difficulty: 'hard', hint: 'trabaja con arcilla y cerámica' },
      { id: 'es-prof-2', text: 'platero', difficulty: 'hard', hint: 'artesano que trabaja con plata' },
      { id: 'es-prof-3', text: 'torero', difficulty: 'medium', hint: 'lidia toros en las corridas' },
      { id: 'es-prof-4', text: 'pescador', difficulty: 'medium', hint: 'captura peces en el mar o ríos' },
      { id: 'es-prof-5', text: 'viñador', difficulty: 'hard', hint: 'cultiva uvas para vino' },
      { id: 'es-prof-6', text: 'herrero', difficulty: 'medium', hint: 'trabaja forjando metal' },
    ],
    languageId: 'es',
    difficulty: 'hard',
  },
  {
    id: 'es-transporte',
    name: 'Transporte Histórico',
    description: 'Medios de transporte tradicionales y modernos',
    words: [
      { id: 'es-trans-1', text: 'calesa', difficulty: 'hard', hint: 'carruaje con caballos' },
      { id: 'es-trans-2', text: 'góndola', difficulty: 'medium', hint: 'barca tradicional de Venecia' },
      { id: 'es-trans-3', text: 'galera', difficulty: 'hard', hint: 'barco antiguo con remeros' },
      { id: 'es-trans-4', text: 'diligencia', difficulty: 'hard', hint: 'carruaje para pasajeros' },
      { id: 'es-trans-5', text: 'tranvía', difficulty: 'medium', hint: 'tren ligero urbano sobre raíles' },
      { id: 'es-trans-6', text: 'funicular', difficulty: 'hard', hint: 'transporte en pendientes pronunciadas' },
    ],
    languageId: 'es',
    difficulty: 'hard',
  },
  {
    id: 'es-heroes',
    name: 'Héroes y Personajes',
    description: 'Figuras históricas y legendarias del mundo hispano',
    words: [
      { id: 'es-hero-1', text: 'Bolívar', difficulty: 'medium', hint: 'libertador de varios países sudamericanos' },
      { id: 'es-hero-2', text: 'Quijote', difficulty: 'medium', hint: 'personaje literario que luchaba contra molinos' },
      { id: 'es-hero-3', text: 'Frida', difficulty: 'easy', hint: 'famosa pintora mexicana' },
      { id: 'es-hero-4', text: 'Neruda', difficulty: 'medium', hint: 'poeta chileno premio Nobel' },
      { id: 'es-hero-5', text: 'Colón', difficulty: 'easy', hint: 'navegante que llegó a América en 1492' },
      { id: 'es-hero-6', text: 'Cortés', difficulty: 'medium', hint: 'conquistador español en México' },
    ],
    languageId: 'es',
    difficulty: 'medium',
  }
];
