
import { Character, Location } from './types';

export const defaultCharacter: Character = {
  name: 'Explorer',
  avatar: '👦',
  currentLocation: 'bedroom',
  inventory: [],
  credits: 0,
  stars: 0,
};

// Initialize with culturally enhanced locations
export const defaultLocations: Location[] = [
  {
    id: 'bedroom',
    name: 'Bedroom',
    room: 'bedroom',
    terrain: 'forest',
    description: 'Your cozy bedroom has transformed into an enchanted forest with tall, magical trees! Can you spot local wildlife and plants?',
    challengeDescription: 'Learn the names of animals, plants, and natural features in your chosen language to navigate through the forest.',
    isLocked: false,
    isCompleted: false,
    requiredPoints: 0,
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    room: 'kitchen',
    terrain: 'desert',
    description: 'The kitchen has become a vast desert with sand dunes and an oasis in the distance! Traditional foods and spices create magical aromas in the air.',
    challengeDescription: 'Master the names of regional dishes, fruits, and food items to find water and sustenance in the desert.',
    isLocked: true,
    isCompleted: false,
    requiredPoints: 50,
  },
  {
    id: 'livingRoom',
    name: 'Living Room',
    room: 'livingRoom',
    terrain: 'river',
    description: 'The living room is now a rushing river with waterfalls and whirlpools! Famous landmarks from the language\'s culture line the riverbanks.',
    challengeDescription: 'Learn about famous rivers, lakes, and water-related words from the culture to safely navigate the currents.',
    isLocked: true,
    isCompleted: false,
    requiredPoints: 100,
  },
  {
    id: 'garden',
    name: 'Garden',
    room: 'garden',
    terrain: 'mountain',
    description: 'Your garden has transformed into towering mountains with snow-capped peaks! Folk tales and legends come alive among the mountain passes.',
    challengeDescription: 'Master words related to mythology, folk stories, and natural wonders to climb to the mountain summit.',
    isLocked: true,
    isCompleted: false,
    requiredPoints: 150,
  },
  {
    id: 'school',
    name: 'School',
    room: 'school',
    terrain: 'castle',
    description: 'Your school is now a magnificent castle inspired by historical architecture! Famous scholars and characters from literature roam the halls.',
    challengeDescription: 'Learn about historical figures, books, and academic terms to solve the castle\'s ancient riddles.',
    isLocked: true,
    isCompleted: false,
    requiredPoints: 200,
  },
  {
    id: 'market',
    name: 'Market',
    room: 'market',
    terrain: 'space',
    description: 'The market has become a colorful festival in space! Traditional crafts, music, and cultural celebrations float among the stars.',
    challengeDescription: 'Master vocabulary related to celebrations, arts, music and cultural traditions to engage with the cosmic festival.',
    isLocked: true,
    isCompleted: false,
    requiredPoints: 250,
  },
];
